version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis-pass
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: redis-server --requirepass "test1234" --appendonly yes

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-ui
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379:0:test1234
    ports:
      - "8081:8081"
    depends_on:
      - redis